import { CourseProps, Student } from 'types';
import annabel from '../annabel.png';

import { cupons } from './Coupons';

export const coursesStudents: CourseProps[] = [
  {
    id: 1,
    title: 'Desarollo de la voz',
    duration: 2,
    inizializationDate: new Date('2023-12-25').toString(),
    quotes: [
      { amount: 200, quantity: 7, quoteNumber: 1 },
      { amount: 200, quantity: 7, quoteNumber: 2 },
      { amount: 200, quantity: 7, quoteNumber: 3 },
      { amount: 200, quantity: 7, quoteNumber: 4 },
    ],
    payments: [{ totalQuotas: 7, totalPrice: 1200 }],
    price: 0.0,
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nostrum ipsum odit laborum tenetur ratione cupiditate laboriosam, quasi totam, expedita magni porro eos. Maiores magnam sunt eos facilis suscipit numquam explicabo.',
    studentsIds: [{ id: 1 }, { id: 3 }, { id: 4 }],
    professorsIds: [{ id: 2 }],
  },
  {
    id: 2,
    title: 'Sarasa',
    duration: 8,
    inizializationDate: new Date('2024-1-25').toString(),
    quotes: [{ amount: 200, quantity: 1, quoteNumber: 1 }],
    payments: [{ totalQuotas: 1, totalPrice: 1000 }],
    price: 0.0,
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nostrum ipsum odit laborum tenetur ratione cupiditate laboriosam, quasi totam, expedita magni porro eos. Maiores magnam sunt eos facilis suscipit numquam explicabo.',
    studentsIds: [{ id: 1 }, { id: 3 }, { id: 4 }],
    professorsIds: [{ id: 2 }],
  },
];

const person: Student = {
  id: 1,
  name: 'Lorem',
  lastname: 'Ipsum',
  phone: '+34 666 777 888',
  birthDate: '12/06/1998',
  email: 'email@email.com',
  genre: 'Femenino',
  experienceType: 'Principiante',
  activity: ['Clases individuales', 'Cursos'],
  image: annabel,
  type: 'student',
  bonos: cupons,
  courses: coursesStudents,
  classesDebt: 1,
  professors: ['Felipe Lorem'],
  dropboxLink: 'wwww.google.com',
  questionnaire: true,
};

export const studentList: Array<Student> = [
  person,
  {
    id: 2,
    name: 'Lorem',
    lastname: 'Ipsum',
    phone: '+34 666 777 888',
    birthDate: '12/06/1998',
    email: 'email@email.com',
    genre: 'Femenino',
    experienceType: 'Intermedio',
    activity: ['Clases individuales'],
    image: annabel,
    type: 'student',
    bonos: cupons,
    professors: ['Felipe Forastiere'],
    dropboxLink: 'wwww.google.com',
    questionnaire: true,
  },
  {
    id: 3,
    name: 'Lorem',
    lastname: 'Ipsum',
    phone: '+34 666 777 888',
    birthDate: '12/06/1998',
    email: 'email@email.com',
    genre: 'Otro',
    experienceType: 'Intermedio',
    activity: ['Clases individuales', 'Cursos'],
    image: annabel,
    type: 'student',
    bonos: cupons,
    courses: coursesStudents,
    lastClassDate: new Date('2023-12-25').toString(),
    professors: ['Felipe Lorem'],
    dropboxLink: 'wwww.google.com',
    questionnaire: true,
  },
  {
    id: 4,
    name: 'Lorem',
    lastname: 'Ipsum',
    phone: '+34 666 777 888',
    birthDate: '12/06/1998',
    email: 'email@email.com',
    genre: 'Femenino',
    experienceType: 'Intermedio',
    activity: ['Cursos'],
    image: annabel,
    type: 'student',
    courses: coursesStudents,
    classesDebt: 3,
    professors: ['Felipe Lorem'],
    dropboxLink: 'wwww.google.com',
    questionnaire: true,
  },
  {
    id: 5,
    name: 'Lorem',
    lastname: 'Ipsum',
    phone: '+34 666 777 888',
    birthDate: '12/06/1998',
    email: 'email@email.com',
    genre: 'Masculino',
    experienceType: 'Intermedio',
    activity: ['Clases individuales'],
    image: annabel,
    type: 'student',
    bonos: cupons,
    lastClassDate: new Date('2023-12-25').toString(),
    professors: ['Felipe Lorem'],
    dropboxLink: 'wwww.google.com',
    questionnaire: true,
  },
];
